name: Develop Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: "Update release branch"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install SSH deploy key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          config: |
            Host github.com
              IdentityFile=/home/runner/.ssh/id_rsa
          known_hosts: unnecessary # github.com is added automatically
          if_key_exists: replace

      - name: Merge and build
        uses: ./.github/actions/build-to-release-branch
        with:
          source_branch: main
          release_branch: release
          built_asset_paths: build
          build_script: |
            npm ci
            npm run build
